/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'timeline-events': TimelineEvent;
    awards: Award;
    'media-coverage': MediaCoverage;
    'case-stories': CaseStory;
    partners: Partner;
    locations: Location;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'timeline-events': TimelineEventsSelect<false> | TimelineEventsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'media-coverage': MediaCoverageSelect<false> | MediaCoverageSelect<true>;
    'case-stories': CaseStoriesSelect<false> | CaseStoriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh-TW' | 'en') | ('zh-TW' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    navigation: Navigation;
    'site-footer': SiteFooter;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-footer': SiteFooterSelect<false> | SiteFooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'zh-TW' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | HeroBlock
    | PageHeaderBlock
    | NewsTickerBlock
    | ContentBlock
    | TimelineBlock
    | StatsCardsBlock
    | AwardsBlock
    | ArticleCardsBlock
    | LogoWallBlock
    | QuoteBlock
    | TwoColumnBlock
    | NumberedFeaturesBlock
    | TaCtaBlock
    | VideoBlockBlock
    | MissionCirclesBlock
    | IconFeaturesBlock
    | StepsBlockBlock
    | InfographicBlock
    | TabsBlockBlock
    | PillarCardsBlock
    | MapLocationsBlock
    | PhotoStripBlock
    | CtaBannerBlock
    | CallToActionBlock
    | MediaBlock
    | ArchiveBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 描述圖片內容，供無障礙與 SEO 使用
   */
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'reviewer' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 每張圖可設定各自的標題/副標/按鈕——想全部一樣就填一樣，想每張不同就分別填。圖與文字會一起滑動切換。
   */
  images?:
    | {
        /**
         * 放這張輪播的滿版背景大圖。建議上傳寬度 1920px 以上的橫式照片，畫面主體盡量置中，因為文字會壓在照片中央。
         */
        image: number | Media;
        /**
         * 填這張圖最主要的一句話，顯示在照片中央最大的字。建議 16 個字以內，太長手機會換很多行。
         */
        title?: string | null;
        /**
         * 填主標題下面的補充說明，會接在主標題下一行。建議 30 個字以內。
         */
        subtitle?: string | null;
        /**
         * 想在照片上放一顆可以點的按鈕就填這裡；按鈕文字和連結都填了才會出現。
         */
        cta?: {
          /**
           * 填按鈕上顯示的字，例如「了解更多」。建議 6 個字以內。
           */
          label?: string | null;
          /**
           * 填點按鈕後要前往的網址。站內可以填以斜線開頭的路徑，例如 /about；站外請填完整網址。
           */
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock".
 */
export interface PageHeaderBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填這個頁面的大標題，會顯示在綠帶左側最大的白字。建議 12 個字以內。
   */
  title: string;
  /**
   * 填標題上方的英文小字，通常用大寫，例如 ABOUT。沒有就留空。
   */
  eyebrow?: string | null;
  /**
   * 放綠帶的背景照片，左側會壓上綠色、右側漸層透出照片。建議上傳寬度 1920px 以上的橫式照片，重點畫面放在右半邊比較看得到。不放的話整條會是純綠色。
   */
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeader';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsTickerBlock".
 */
export interface NewsTickerBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 每一筆是一則跑馬燈消息，會輪流向上捲動顯示。可以新增、刪除、拖曳調整順序。
   */
  items?:
    | {
        /**
         * 填一則消息的文字。電腦版只顯示一行、過長會被切掉，建議 25 個字以內。
         */
        text: string;
        /**
         * 想讓這則消息可以點進去就填網址。站內可以填以斜線開頭的路徑，例如 /news/123；站外請填完整網址。不填就只是純文字。
         */
        url?: string | null;
        enabled?: boolean | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsTicker';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填標題前的一行小字，會顯示在綠色圓點後面，通常放英文或分類字，例如 ABOUT。沒有就留空。
   */
  eyebrow?: string | null;
  /**
   * 填這個段落的主標題，會以灰綠色大字顯示。建議 16 個字以內。
   */
  title?: string | null;
  /**
   * 選標題和眉標要靠左還是置中。只有在這個段落沒有放側邊配圖時才會生效。
   */
  align?: ('left' | 'center') | null;
  /**
   * 想在內文下方放一顆按鈕就填按鈕文字，例如「認識創照」。建議 6 個字以內。按鈕文字和連結都填了才會出現。
   */
  ctaLabel?: string | null;
  /**
   * 填點按鈕後要前往的網址。站內可以填以斜線開頭的路徑，例如 /about；站外請填完整網址。
   */
  ctaUrl?: string | null;
  /**
   * 填這個段落的主要內容文字。可以分段、設定粗體、加上 H2／H3／H4 小標和連結。
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 放這個段落旁邊的一張配圖。建議上傳寬度 768px 以上、接近直式或方形的照片。若要多張錯位拼貼（如首頁品牌簡介 3 張情境照），請改用下方「配圖（多張錯位拼貼）」。兩者擇一即可，多張優先。
   */
  image?: (number | null) | Media;
  /**
   * 依 Figma 首頁品牌簡介排列：第 1 張上方主圖、第 2 張右下小圖、第 3 張左下寬圖。可加／刪／拖曳排序，建議 3 張。每張建議上傳寬度 768px 以上的橫式照片。
   */
  images?:
    | {
        /**
         * 放一張情境照。建議上傳寬度 768px 以上、接近 4:3 的橫式照片。
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 選配圖要放在文字的哪一邊，或放在文字下方一整排。選「不顯示」就不會出現配圖。
   */
  imagePosition?: ('left' | 'right' | 'belowCenter' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選大事紀要怎麼來。選「手動輸入」就在下方一筆筆自己打；選「引用大事紀資料」就從共用的大事紀資料庫挑要顯示的項目。
   */
  mode: 'manual' | 'reference';
  /**
   * 每一筆是時間軸上的一個事件，會由上到下依序排列。可以新增、刪除、拖曳調整順序。
   */
  items?:
    | {
        /**
         * 填這個事件的年份或日期，例如 2020 或 2020/03。
         */
        date: string;
        /**
         * 填這個事件的標題，會顯示在綠色的圓角標籤裡。建議 14 個字以內。
         */
        title: string;
        /**
         * 填這個事件的補充說明，只有在下方打開「顯示每筆說明文字」時才會出現。建議 25 個字以內。
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 從共用的大事紀資料庫挑出要顯示的項目，可以挑多筆。系統會自動依年份排序。
   */
  events?: (number | TimelineEvent)[] | null;
  /**
   * 打開後，每個事件的標籤下面會多顯示一句話描述。關閉時只顯示乾淨的單行標籤。
   */
  showDescription?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events".
 */
export interface TimelineEvent {
  id: number;
  /**
   * 西元年，例如 2017
   */
  year: number;
  title: string;
  description?: string | null;
  /**
   * 數字小的排前面；同年份可用此欄位調整先後
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsCardsBlock".
 */
export interface StatsCardsBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 一張卡片是一個數據，例如「服務 120 個家庭」。可以新增多張並排顯示，建議放 3 到 4 張最整齊。
   */
  cards?:
    | {
        /**
         * 填想強調的數字，例如 120、98。會以大字顯示，請只填數字本身，單位放在後綴欄。
         */
        number: string;
        /**
         * 填數字下方的一行說明，例如「服務家庭數」「合作鄉鎮」。簡短一句最好看。
         */
        label: string;
        /**
         * 填數字後面的單位，例如「人」「%」「個」。沒有單位可以留空。
         */
        suffix?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardsBlock".
 */
export interface AwardsBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選「手動輸入」就在這個區塊直接打獎項；選「引用獎項資料」則改從獎項資料庫挑選，適合多個頁面共用同一份清單。
   */
  source: 'manual' | 'collection';
  /**
   * 從獎項資料庫挑選要顯示的獎項，可以選多筆。畫面會自動依年份由新到舊排序。
   */
  awards?: (number | Award)[] | null;
  /**
   * 一筆一個獎項，會以條列清單顯示在左欄。可以新增多筆，建議由新到舊排列。
   */
  items?:
    | {
        /**
         * 填西元年份，例如 2025。
         */
        year: string;
        /**
         * 填月份數字，例如 6。不確定月份可以留空。
         */
        month?: string | null;
        /**
         * 填完整的獎項名稱，例如「第 12 屆台灣社會企業獎」。
         */
        name: string;
        /**
         * 填補充說明或得獎單位，例如「金獎」「年度團隊」。會顯示在獎項名稱後面，可以留空。
         */
        recipient?: string | null;
        /**
         * 放這組獎項要搭配的照片，會顯示在右側大圖位置。建議上傳寬度 1920px 以上的橫式照片。多筆獎項只會取其中一張當代表圖。
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'awards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  /**
   * 西元年，例如 2023
   */
  year: number;
  /**
   * 選填，1–12
   */
  month?: number | null;
  name: string;
  /**
   * 例如獲獎單位別稱或獎項簡稱，選填
   */
  alias?: string | null;
  /**
   * 選填
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleCardsBlock".
 */
export interface ArticleCardsBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選資料來源：「案例故事」「媒體報導」會自動抓對應資料庫的內容；選「手動卡片」則在這個區塊自己一張一張填。
   */
  source: 'case-stories' | 'media-coverage' | 'manual';
  /**
   * 填標題上方的英文小字，例如 Media。只在媒體報導版型顯示，可以留空。
   */
  eyebrow?: string | null;
  /**
   * 填媒體報導區塊右側的大標題，例如「媒體報導」。只在媒體報導版型顯示。
   */
  heading?: string | null;
  /**
   * 放媒體報導區塊左側的代表圖。建議上傳寬度 1920px 以上的橫式照片，顯示時會裁成接近 3:2 的比例。
   */
  leadImage?: (number | null) | Media;
  /**
   * 設定一開始顯示幾張卡片，例如填 3 就先顯示 3 張，其餘按「載入更多」才出現。
   */
  batchSize?: number | null;
  /**
   * 勾選後，卡片數量超過上面設定時會出現「載入更多」按鈕。取消勾選則只顯示前面那批。
   */
  enableLoadMore?: boolean | null;
  /**
   * 一張卡片是一則內容，例如一篇報導或一個故事。只有資料來源選「手動卡片」時才需要填。
   */
  cards?:
    | {
        /**
         * 放這張卡片的圖片。建議上傳寬度 768px 以上、接近 4:3 的橫式圖，顯示時會自動裁切置中。
         */
        image?: (number | null) | Media;
        /**
         * 填卡片標題，也就是這則內容的名稱，例如報導或故事的篇名。
         */
        title: string;
        /**
         * 填標題下方的一兩句簡介，讓讀者快速知道內容在講什麼。可以留空。
         */
        excerpt?: string | null;
        /**
         * 填點擊卡片後要前往的網址，例如原始報導連結。記得連 https:// 一起填。沒有連結可以留空。
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articleCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock".
 */
export interface LogoWallBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選「手動輸入」就在這個區塊直接上傳每個 Logo；選「夥伴資料」則自動抓夥伴資料庫的 Logo。
   */
  source: 'partners' | 'manual';
  /**
   * 只想顯示某一類夥伴時填類別名稱，留空就顯示全部夥伴。
   */
  partnerType?: string | null;
  /**
   * 一筆一個 Logo，會並排顯示成一面 Logo 牆。可以新增多個。
   */
  logos?:
    | {
        /**
         * 上傳這個夥伴的 Logo。建議用 SVG 或去背的 PNG，背景透明在白底卡片上最好看。
         */
        logo: number | Media;
        /**
         * 填這個 Logo 代表的單位名稱。畫面上不會直接顯示，是給點擊連結與無障礙朗讀用的，建議照樣填寫。
         */
        name?: string | null;
        /**
         * 填點擊 Logo 後要前往的網址，例如對方官網。記得連 https:// 一起填。沒有連結可以留空。
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoWall';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填想凸顯的一段話或推薦語，會以置中大字顯示。系統會自動加上「」引號，不用自己打。
   */
  text: string;
  /**
   * 填說這句話的人或單位，例如「林依瑩 執行長」。會顯示在引言下方，可以留空。
   */
  attribution?: string | null;
  /**
   * 放說這句話的人的大頭照，會顯示成引言上方的圓形頭像。建議上傳正方形、600px 以上的照片。
   */
  photo?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock".
 */
export interface TwoColumnBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  direction: 'imageLeft' | 'imageRight';
  variant?: ('standard' | 'hero' | 'quotes' | 'centered') | null;
  /**
   * 填一句最上面的粗體前導標題，可以不填。想要分行的地方輸入 \n。建議在 30 個字以內，超過會擠到版面。
   */
  lead?: string | null;
  background?: ('none' | 'surface') | null;
  /**
   * 填標題上方的一行英文小標，例如 Service，可以不填。建議在 12 個字母以內，只放一行短字。
   */
  eyebrow?: string | null;
  /**
   * 上傳這個區塊的主圖。建議上傳寬度 768px 以上、接近 4:3 的橫式照片；如果是大圖引言版型，建議上傳寬度 1920px 以上的橫式大圖。
   */
  image: number | Media;
  /**
   * 想要做斜疊雙圖時，放滿兩張照片即可。只放一張或不放，就會使用上面的單張主圖。建議兩張都上傳寬度 768px 以上的橫式照片。
   */
  images?:
    | {
        /**
         * 上傳一張橫式照片，建議寬度 768px 以上。
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 填這個區塊的主標題。建議在 20 個字以內，太長會換很多行。
   */
  title?: string | null;
  /**
   * 填這個區塊的內文段落，可以分段、加上小標或粗體。
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 想在內文下方放一顆按鈕時，填按鈕文字和連結；兩個都填才會顯示。
   */
  cta?: {
    /**
     * 填按鈕上的文字，例如 了解更多。建議在 6 個字以內。
     */
    label?: string | null;
    /**
     * 填按鈕點下去要前往的網址。站內頁面用斜線開頭，例如 /about；站外網址請填完整的 https 連結。
     */
    url?: string | null;
  };
  items?:
    | {
        /**
         * 上傳這張卡的圖示或照片，可以不填，不填會用預設的圓形色塊。圖示建議用 SVG 或去背 PNG；照片建議正方形、寬度 600px 以上。
         */
        image?: (number | null) | Media;
        /**
         * 填這張卡的標題。建議在 10 個字以內。
         */
        title: string;
        /**
         * 填這張卡的一兩句說明，可以不填。建議在 40 個字以內。
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  itemsStyle?: ('iconCards' | 'steps' | 'pillars' | 'grid' | 'pathway') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'twoColumn';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedFeaturesBlock".
 */
export interface NumberedFeaturesBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填整區最上方的一行英文小標，例如 Service，可以不填。只會顯示在第一個項目上方，建議在 12 個字母以內。
   */
  eyebrow?: string | null;
  items?:
    | {
        /**
         * 填這個項目的序號，例如 01、02、03。只放兩位數字就好。
         */
        number: string;
        /**
         * 填這個項目的標題。建議在 14 個字以內，太長會擠到旁邊的序號。
         */
        title: string;
        /**
         * 填這個項目的說明段落，可以多行，按 Enter 換行就會分行顯示。
         */
        text: string;
        /**
         * 上傳這個項目右側（或左側）的照片。建議上傳寬度 768px 以上、接近 3:2 的橫式照片。
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'numberedFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaCtaBlock".
 */
export interface TaCtaBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  variant: 'tiles' | 'photoCards' | 'photoBand' | 'darkBand';
  /**
   * 填照片連結卡上方的一段置中導言，可以多行，按 Enter 換行。建議在 40 個字以內。只有照片連結雙卡版型會用到。
   */
  intro?: string | null;
  cards?:
    | {
        /**
         * 三磚版型上傳白色去背的線稿插圖，建議用 SVG 或去背 PNG，不填會用預設插圖；照片卡與全幅照片帶請上傳橫式照片，照片卡建議寬度 768px 以上、全幅照片帶建議寬度 1920px 以上。
         */
        image?: (number | null) | Media;
        /**
         * 填這張卡的標語，例如 我想成為照顧專業人才。建議在 14 個字以內，太長會換行。
         */
        title: string;
        /**
         * 填按鈕上的文字，例如 立即了解。建議在 8 個字以內。照片連結卡不放按鈕，可以留空。
         */
        buttonLabel?: string | null;
        /**
         * 填這張卡點下去要前往的網址。站內頁面用斜線開頭，例如 /school；頁內錨點用井號開頭，例如 #sheet；站外網址請填完整的 https 連結。
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'taCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockBlock".
 */
export interface VideoBlockBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 貼上 YouTube 影片連結（watch、youtu.be、shorts、embed 都可以），或填一個 mp4 影片檔的網址。影片還沒準備好可以先留空，點播放鈕會顯示即將上線的提示。
   */
  videoUrl?: string | null;
  /**
   * 上傳影片未播放時顯示的封面圖。建議上傳寬度 1920px 以上的橫式大圖，比例接近 16:9。不填會顯示灰底佔位。
   */
  poster?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionCirclesBlock".
 */
export interface MissionCirclesBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  variant: 'band' | 'plain';
  /**
   * 填白底版型最上方的置中標題，例如 \ 與我們一起行動 /。建議在 14 個字以內。只有白底行動三圓版型會用到。
   */
  title?: string | null;
  /**
   * 填宣言帶上方的標語，可以多行，按 Enter 換行就會分行顯示。建議在 30 個字以內。只有宣言帶版型會用到。
   */
  slogan?: string | null;
  /**
   * 上傳宣言帶的背景照片。建議上傳寬度 1920px 以上的橫式大圖。只有宣言帶版型會用到。
   */
  backgroundImage?: (number | null) | Media;
  circles?:
    | {
        /**
         * 填顯示在圓圈裡的白色短句，例如 培育照顧的人。建議在 8 個字以內。
         */
        label: string;
        /**
         * 填圓圈下方的一兩句說明，可以不填。建議在 30 個字以內。只有白底行動三圓版型會顯示。
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'missionCircles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFeaturesBlock".
 */
export interface IconFeaturesBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選擇卡片排列方式。米色橫卡列適合放一排功能或步驟說明，建議放 4 個項目；直立綠卡是站立式色卡，建議放 5 個項目；學員角色是 icon 在上、標題說明置中的 4 欄版型。
   */
  variant: 'cards' | 'pillars' | 'roles';
  /**
   * 只有「學員角色」版型會用到，顯示在卡片上方（例如「學員樣貌」）；其他版型可留空。
   */
  heading?: string | null;
  /**
   * 逐一新增每一張卡片的內容。米色橫卡列建議放 4 個，直立綠卡建議放 5 個。
   */
  items?:
    | {
        /**
         * 上傳這張卡片的小圖示。建議上傳 SVG 或去背 PNG。不上傳時會自動帶入系統內建的線稿圖示。
         */
        icon?: (number | null) | Media;
        /**
         * 填這張卡片的標題，請簡短，建議 16 個字以內，太長會擠壓版面。
         */
        title: string;
        /**
         * 填標題底下的補充說明，一兩句話即可，建議 60 個字以內。
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconFeatures';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlockBlock".
 */
export interface StepsBlockBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選擇步驟的呈現方式。整寬米色卡適合放服務流程，步驟間有箭頭相連；橫列版適合放發展路徑；外框卡適合放並列的成果或影響力。建議放 3 個步驟。
   */
  variant: 'cardRow' | 'inline' | 'outline';
  /**
   * 填整個步驟區上方的標題，可以不填。建議 30 個字以內。
   */
  title?: string | null;
  /**
   * 逐一新增每一個步驟，建議放 3 個，並依照流程先後順序排列。
   */
  items?:
    | {
        /**
         * 上傳這個步驟的小圖示，建議上傳 SVG 或去背 PNG。不上傳時會自動帶入系統內建的線稿圖示。外框卡版型不會顯示圖示，可以不填。
         */
        icon?: (number | null) | Media;
        /**
         * 填這個步驟的標題，請簡短，建議 16 個字以內。外框卡版型可以留空。
         */
        title?: string | null;
        /**
         * 填步驟的補充說明，一兩句話即可，建議 50 個字以內。
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stepsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfographicBlock".
 */
export interface InfographicBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 選擇資訊圖的樣式。兩圓圖適合用兩個面向＋數字呈現現況痛點；環形圖適合在環上放四張照片帶出問題；菱形四圓適合並列四個面向。選好圖型後，下方會出現對應要填的欄位。
   */
  variant: 'venn' | 'ring' | 'radial';
  /**
   * 填標題上方的英文小標，例如一個英文短語，可以不填。填了標題或內文後，圖會移到右邊、文字在左邊。建議 30 個字以內。
   */
  eyebrow?: string | null;
  /**
   * 填左邊欄位的大標題，可以不填。標題和內文都不填時，資訊圖會置中放大滿版。建議 30 個字以內。
   */
  title?: string | null;
  /**
   * 填左邊欄位的說明文字。按 Enter 換行就會分段；在開頭加「・」可以做成項目符號。
   */
  body?: string | null;
  /**
   * 填左邊大圓中央的標題，例如「個人生活」。請簡短，建議 8 個字以內。
   */
  leftLabel?: string | null;
  /**
   * 填右邊大圓中央的標題，例如「職場角色」。請簡短，建議 8 個字以內。
   */
  rightLabel?: string | null;
  /**
   * 左邊大圓周圍的小數據圓，最多放 3 顆，每顆放一組數字加說明。
   */
  leftStats?:
    | {
        /**
         * 填要強調的數字，例如「8+」或「6成」。請簡短，建議 8 個字以內。
         */
        value: string;
        /**
         * 填數字底下的說明，例如「平均照顧年數」。請簡短，建議 12 個字以內。
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 右邊大圓周圍的小數據圓，最多放 3 顆，每顆放一組數字加說明。
   */
  rightStats?:
    | {
        /**
         * 填要強調的數字，例如「13.3萬」。請簡短，建議 8 個字以內。
         */
        value: string;
        /**
         * 填數字底下的說明文字。請簡短，建議 12 個字以內。
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 放在環形圖四角的照片，請放 4 張，順序為右上、右下、左下、左上。
   */
  photos?:
    | {
        /**
         * 上傳一張照片，顯示時會裁成圓形。建議上傳正方形、寬度 600px 以上的照片，主體放中間比較不會被裁掉。
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 菱形排列的四個圓，請放 4 個，順序為上、左、右、下，每個圓放一個面向。
   */
  nodes?:
    | {
        /**
         * 上傳圓內的小圖示，建議上傳 SVG 或去背 PNG，可以不填。不上傳時會自動帶入系統內建的線稿圖示。
         */
        icon?: (number | null) | Media;
        /**
         * 填這個圓的標題，請簡短，建議 16 個字以內。
         */
        title: string;
        /**
         * 填標題底下的補充說明，一兩句話即可，建議 40 個字以內。
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'infographic';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlockBlock".
 */
export interface TabsBlockBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填整個區塊最上方的置中大標題，可以不填。建議 40 個字以內。
   */
  title?: string | null;
  /**
   * 填標題底下的置中導言，按 Enter 換行就會分行。建議 80 個字以內。
   */
  intro?: string | null;
  /**
   * 逐一新增每一個分頁。訪客點上方的分頁按鈕，下方面板就會切換成對應內容。版型最適合 4 個分頁。
   */
  tabs?:
    | {
        /**
         * 填分頁按鈕上的文字，例如「課程地圖」。請很簡短，建議 10 個字以內。
         */
        label: string;
        /**
         * 上傳這個分頁面板最上方的大圖，例如地圖或圖表。建議上傳寬度 1075px 以上、接近 16:9 的橫式圖。
         */
        image?: (number | null) | Media;
        /**
         * 大圖底下一整排的小圓角標籤，逐一新增，每個標籤填一個關鍵詞。
         */
        pills?:
          | {
              /**
               * 填一個標籤的文字，請簡短，建議 12 個字以內。
               */
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * 填面板內的大標題，例如「課程地圖」。請簡短，建議 16 個字以內。
         */
        heading?: string | null;
        /**
         * 填標題底下的橄欖綠色小標一句話，建議 30 個字以內。
         */
        subheading?: string | null;
        /**
         * 填面板的主要說明文字，按 Enter 換行就會分段。
         */
        body?: string | null;
        /**
         * 填特色清單上方的小標題，例如「學習特色」。建議 16 個字以內。
         */
        featuresLabel?: string | null;
        /**
         * 逐一新增這個分頁要列出的特色，每一項一個標題加一段說明。
         */
        features?:
          | {
              /**
               * 填這一項特色的標題，請簡短，建議 20 個字以內。
               */
              title: string;
              /**
               * 填這一項特色的說明文字，建議 80 個字以內。
               */
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tabsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarCardsBlock".
 */
export interface PillarCardsBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填標題上方的英文小標，可以不填。建議 30 個字以內。
   */
  eyebrow?: string | null;
  /**
   * 填這個區塊的主標題，例如「人才培育系統」。建議 20 個字以內。
   */
  title?: string | null;
  /**
   * 填標題底下的副標一句話，建議 30 個字以內。
   */
  subtitle?: string | null;
  /**
   * 填右邊欄位的導言段落，按 Enter 換行就會分段。
   */
  intro?: string | null;
  /**
   * 逐一新增直立色卡，建議放 4 張。卡片底色會依新增順序自動套用，並一高一低交錯排列，不需要自己設定。
   */
  cards?:
    | {
        /**
         * 填卡片頂端的小標籤，例如「學習的內容」。請很簡短，建議 10 個字以內。
         */
        tag?: string | null;
        /**
         * 上傳卡片白色圓圈內的小圖示，建議上傳 SVG 或去背 PNG，可以不填。不上傳時會自動帶入系統內建的線稿圖示。
         */
        icon?: (number | null) | Media;
        /**
         * 填卡片的主標大字，例如「課程」。請很簡短，建議 6 個字以內。
         */
        titleMain: string;
        /**
         * 填主標旁邊接著的小字，例如「地圖」，可以不填。建議 6 個字以內。
         */
        titleSub?: string | null;
        /**
         * 填卡片底部的說明文字，約兩行，建議 40 個字以內。
         */
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pillarCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapLocationsBlock".
 */
export interface MapLocationsBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填一行小標，放在主標題上方，可以放英文或服務名稱，例如 CFT Space。
   */
  eyebrow?: string | null;
  /**
   * 填這個區塊的大標題，建議在 12 個字以內，例如：羅布森空間。
   */
  title?: string | null;
  /**
   * 填一句副標，放在標題下方，用來補充說明，例如：照顧學校的培訓場域。
   */
  subtitle?: string | null;
  /**
   * 填這個區塊的說明文字，按一次換行就會分成一個新段落。
   */
  body?: string | null;
  /**
   * 上傳一張地圖插畫放在右側。建議上傳寬度 600px 以上、橫式的圖。如果留空，系統會自動顯示內建的水彩地形圖。
   */
  image?: (number | null) | Media;
  /**
   * 一個一個加上要標記在地圖上的據點，每個據點會在地圖上顯示一個定位圖釘和名稱。
   */
  locations?:
    | {
        /**
         * 填這個據點的中文名稱，例如：臺中溪尾。
         */
        name: string;
        /**
         * 填這個據點的英文名稱（可以不填），會顯示在中文名稱下方。
         */
        nameEn?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mapLocations';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoStripBlock".
 */
export interface PhotoStripBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 勾選後，在電腦上捲動頁面時整條照片帶會緩慢橫向移動，做出動態效果。不確定可以不勾。
   */
  parallax?: boolean | null;
  /**
   * 一張一張加上要排成橫帶的照片，建議放 5 張、方向一致（都用橫式或都用直式），畫面才會整齊。
   */
  images?:
    | {
        /**
         * 上傳一張照片。建議每張寬度 1200px 以上、方向和其他照片一致，會以接近 4:3 置中裁切顯示。
         */
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'photoStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock".
 */
export interface CtaBannerBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填這個橫幅最大的一句話，用來吸引讀者，建議在 15 個字以內。
   */
  title: string;
  /**
   * 填一句補充說明，放在主標題下方（可以不填），建議在 30 個字以內。
   */
  subtitle?: string | null;
  /**
   * 設定橫幅下方的按鈕；按鈕文字和連結網址兩格都要填，按鈕才會出現。
   */
  cta?: {
    /**
     * 填按鈕上顯示的文字，建議在 6 個字以內，例如：立即聯絡、了解更多。
     */
    label?: string | null;
    /**
     * 填按下按鈕後要前往的網址，可以放本站頁面（例如 /contact）或完整外部網址。
     */
    url?: string | null;
  };
  /**
   * 選這個橫幅的底色，從主色、輔色、淺色底、深色底四種品牌色裡挑一個。
   */
  background: 'primary' | 'secondary' | 'muted' | 'dark';
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 填這個區塊左側要顯示的文字，可以設定標題與段落；右側的按鈕請在下方「連結」設定。
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * 放在內文中間的圖片。建議上傳寬度 1200px 以上的清晰圖片。如果想加圖說，請到媒體庫的這張圖片裡填寫「caption」說明文字。
   */
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  /**
   * 取消勾選即可在網站上隱藏此區塊，內容仍會保留，隨時可再次勾選顯示。
   */
  enabled?: boolean | null;
  /**
   * 這個區塊會自動把最新消息或文章列出來。這裡填寫列表上方的開頭文字，例如一個標題或一段簡短說明，可以留空。
   */
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 選擇要怎麼挑文章。選「Collection」會依分類自動帶出最新文章，選「Individual Selection」則由你逐一手動指定要顯示哪幾篇。
   */
  populateBy?: ('collection' | 'selection') | null;
  /**
   * 選擇要從哪一種內容自動列出，目前可以選文章（Posts）。
   */
  relationTo?: 'posts' | null;
  /**
   * 選擇要顯示哪些分類的文章，可以複選。留空的話會列出所有分類的最新文章。
   */
  categories?: (number | Category)[] | null;
  /**
   * 填入最多要顯示幾篇文章，例如填 6 就是最多列出 6 篇。
   */
  limit?: number | null;
  /**
   * 逐一挑選想要顯示的文章，顯示順序就是你加入的先後順序。
   */
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-coverage".
 */
export interface MediaCoverage {
  id: number;
  title: string;
  /**
   * 例如：聯合報、天下雜誌
   */
  outlet: string;
  date: string;
  /**
   * 完整網址，例如 https://...
   */
  url: string;
  /**
   * 前台卡片顯示的簡短摘要，選填
   */
  excerpt?: string | null;
  /**
   * 選填，未提供時前台可用預設樣式
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-stories".
 */
export interface CaseStory {
  id: number;
  title: string;
  /**
   * 列表卡片顯示的簡短摘要
   */
  summary: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image: number | Media;
  /**
   * 這則案例故事要出現在哪個頁面
   */
  page: 'care' | 'training';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * 選填，完整網址，例如 https://...
   */
  url?: string | null;
  type: 'partner' | 'family';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  address: string;
  description?: string | null;
  /**
   * 選填
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'timeline-events';
        value: number | TimelineEvent;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'media-coverage';
        value: number | MediaCoverage;
      } | null)
    | ({
        relationTo: 'case-stories';
        value: number | CaseStory;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        pageHeader?: T | PageHeaderBlockSelect<T>;
        newsTicker?: T | NewsTickerBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        statsCards?: T | StatsCardsBlockSelect<T>;
        awards?: T | AwardsBlockSelect<T>;
        articleCards?: T | ArticleCardsBlockSelect<T>;
        logoWall?: T | LogoWallBlockSelect<T>;
        quote?: T | QuoteBlockSelect<T>;
        twoColumn?: T | TwoColumnBlockSelect<T>;
        numberedFeatures?: T | NumberedFeaturesBlockSelect<T>;
        taCta?: T | TaCtaBlockSelect<T>;
        videoBlock?: T | VideoBlockBlockSelect<T>;
        missionCircles?: T | MissionCirclesBlockSelect<T>;
        iconFeatures?: T | IconFeaturesBlockSelect<T>;
        stepsBlock?: T | StepsBlockBlockSelect<T>;
        infographic?: T | InfographicBlockSelect<T>;
        tabsBlock?: T | TabsBlockBlockSelect<T>;
        pillarCards?: T | PillarCardsBlockSelect<T>;
        mapLocations?: T | MapLocationsBlockSelect<T>;
        photoStrip?: T | PhotoStripBlockSelect<T>;
        ctaBanner?: T | CtaBannerBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  enabled?: T;
  images?:
    | T
    | {
        image?: T;
        title?: T;
        subtitle?: T;
        cta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeaderBlock_select".
 */
export interface PageHeaderBlockSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  eyebrow?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsTickerBlock_select".
 */
export interface NewsTickerBlockSelect<T extends boolean = true> {
  enabled?: T;
  items?:
    | T
    | {
        text?: T;
        url?: T;
        enabled?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  title?: T;
  align?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  richText?: T;
  image?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  imagePosition?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  enabled?: T;
  mode?: T;
  items?:
    | T
    | {
        date?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  events?: T;
  showDescription?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsCardsBlock_select".
 */
export interface StatsCardsBlockSelect<T extends boolean = true> {
  enabled?: T;
  cards?:
    | T
    | {
        number?: T;
        label?: T;
        suffix?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AwardsBlock_select".
 */
export interface AwardsBlockSelect<T extends boolean = true> {
  enabled?: T;
  source?: T;
  awards?: T;
  items?:
    | T
    | {
        year?: T;
        month?: T;
        name?: T;
        recipient?: T;
        photo?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleCardsBlock_select".
 */
export interface ArticleCardsBlockSelect<T extends boolean = true> {
  enabled?: T;
  source?: T;
  eyebrow?: T;
  heading?: T;
  leadImage?: T;
  batchSize?: T;
  enableLoadMore?: T;
  cards?:
    | T
    | {
        image?: T;
        title?: T;
        excerpt?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoWallBlock_select".
 */
export interface LogoWallBlockSelect<T extends boolean = true> {
  enabled?: T;
  source?: T;
  partnerType?: T;
  logos?:
    | T
    | {
        logo?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  enabled?: T;
  text?: T;
  attribution?: T;
  photo?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnBlock_select".
 */
export interface TwoColumnBlockSelect<T extends boolean = true> {
  enabled?: T;
  direction?: T;
  variant?: T;
  lead?: T;
  background?: T;
  eyebrow?: T;
  image?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  title?: T;
  richText?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  items?:
    | T
    | {
        image?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  itemsStyle?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedFeaturesBlock_select".
 */
export interface NumberedFeaturesBlockSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  items?:
    | T
    | {
        number?: T;
        title?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaCtaBlock_select".
 */
export interface TaCtaBlockSelect<T extends boolean = true> {
  enabled?: T;
  variant?: T;
  intro?: T;
  cards?:
    | T
    | {
        image?: T;
        title?: T;
        buttonLabel?: T;
        url?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlockBlock_select".
 */
export interface VideoBlockBlockSelect<T extends boolean = true> {
  enabled?: T;
  videoUrl?: T;
  poster?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionCirclesBlock_select".
 */
export interface MissionCirclesBlockSelect<T extends boolean = true> {
  enabled?: T;
  variant?: T;
  title?: T;
  slogan?: T;
  backgroundImage?: T;
  circles?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFeaturesBlock_select".
 */
export interface IconFeaturesBlockSelect<T extends boolean = true> {
  enabled?: T;
  variant?: T;
  heading?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlockBlock_select".
 */
export interface StepsBlockBlockSelect<T extends boolean = true> {
  enabled?: T;
  variant?: T;
  title?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InfographicBlock_select".
 */
export interface InfographicBlockSelect<T extends boolean = true> {
  enabled?: T;
  variant?: T;
  eyebrow?: T;
  title?: T;
  body?: T;
  leftLabel?: T;
  rightLabel?: T;
  leftStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  rightStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  photos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  nodes?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TabsBlockBlock_select".
 */
export interface TabsBlockBlockSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  intro?: T;
  tabs?:
    | T
    | {
        label?: T;
        image?: T;
        pills?:
          | T
          | {
              text?: T;
              id?: T;
            };
        heading?: T;
        subheading?: T;
        body?: T;
        featuresLabel?: T;
        features?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarCardsBlock_select".
 */
export interface PillarCardsBlockSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  intro?: T;
  cards?:
    | T
    | {
        tag?: T;
        icon?: T;
        titleMain?: T;
        titleSub?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MapLocationsBlock_select".
 */
export interface MapLocationsBlockSelect<T extends boolean = true> {
  enabled?: T;
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  body?: T;
  image?: T;
  locations?:
    | T
    | {
        name?: T;
        nameEn?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoStripBlock_select".
 */
export interface PhotoStripBlockSelect<T extends boolean = true> {
  enabled?: T;
  parallax?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBannerBlock_select".
 */
export interface CtaBannerBlockSelect<T extends boolean = true> {
  enabled?: T;
  title?: T;
  subtitle?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  enabled?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  enabled?: T;
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  enabled?: T;
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline-events_select".
 */
export interface TimelineEventsSelect<T extends boolean = true> {
  year?: T;
  title?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  year?: T;
  month?: T;
  name?: T;
  alias?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-coverage_select".
 */
export interface MediaCoverageSelect<T extends boolean = true> {
  title?: T;
  outlet?: T;
  date?: T;
  url?: T;
  excerpt?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-stories_select".
 */
export interface CaseStoriesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  body?: T;
  image?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * 拖拉可調整順序
   */
  items?:
    | {
        label: string;
        type: 'internal' | 'external';
        /**
         * 內部頁填路徑（例如 /about）；外連填完整網址（例如 https://school.carefortaiwan.com.tw）
         */
        url: string;
        highlight?: boolean | null;
        /**
         * 選填；有子項目時前台顯示下拉選單，拖拉可調整順序
         */
        subItems?:
          | {
              label: string;
              type: 'internal' | 'external';
              /**
               * 內部頁填路徑（例如 /about）；外連填完整網址（例如 https://school.carefortaiwan.com.tw）
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer".
 */
export interface SiteFooter {
  id: number;
  /**
   * 頁尾的連結欄位，拖拉可調整順序
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * 內部頁填路徑（例如 /care）；外連填完整網址
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 例如：創照服務設計、照顧學校、伯拉罕、鄰里123、Connect 10
   */
  familyVentures?:
    | {
        name: string;
        /**
         * 選填，完整網址
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'youtube' | 'line' | 'linkedin' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 例如：© 2026 創照服務設計有限公司 All rights reserved.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * 聯絡表單送出後，通知信會寄到這些信箱（可多個）
   */
  inquiryRecipients?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 系統寄出通知信時使用的寄件人，需先在 SES 完成驗證
   */
  sesSender?: string | null;
  /**
   * 選填，例如 G-XXXXXXXXXX；目前僅保留欄位，前台尚未接
   */
  gaId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        type?: T;
        url?: T;
        highlight?: T;
        subItems?:
          | T
          | {
              label?: T;
              type?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-footer_select".
 */
export interface SiteFooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  familyVentures?:
    | T
    | {
        name?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  inquiryRecipients?:
    | T
    | {
        email?: T;
        id?: T;
      };
  sesSender?: T;
  gaId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  /**
   * 選一個提示樣式來決定底色與外框。Info 是一般說明（藍灰），Warning 是提醒注意（黃），Error 是錯誤或重要警告（紅），Success 是成功或好消息（綠）。
   */
  style: 'info' | 'warning' | 'error' | 'success';
  /**
   * 填入要強調顯示的提示文字，建議一兩句話就好，太長會讓提示框變得擁擠。
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  /**
   * 這個區塊是給開發人員放程式碼或嵌入碼用的，一般內容編輯不需要用到。這裡選擇程式碼的語言，決定顏色標示的方式。
   */
  language?: ('typescript' | 'javascript' | 'css') | null;
  /**
   * 貼上程式碼或嵌入用的代碼。這是技術性欄位，多數客戶不會用到，如果不確定可以略過這個區塊。
   */
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}